### ISSUE TITLE
Button "Add to favorites" does not work

### ISSUE THREAD

**Issue by marinkaberg** [CorentinTh/it-tools#1424]
### Describe the bug

Add to favorites does not work for FF and Chrome till 2024.5.13-a0bc346 (I use Docker instance).

### What happened?

Just nothing happens when you click on the "Add to favorites" button.

### System information

Nginx reverse proxy, IT-Tools in Docker container.
I tried several containers, in 2024.10.22-7ca5933 the button doesn't work, but in 2024.5.13-a0bc346 and in 2023.12.21-5ed3693 it does. The older ones I haven't tested.
Button "Add to favorites" at https://it-tools.tech works fine ;)

### Where did you encounter the bug?

A self hosted

**Comment by r007d4nc3** [comment]
Same here (proxmox LXC / docker, not working with Chrome and Safari).
As a work around you can add to favorites in the main page under "all the tools"

**Comment by vineet3996** [comment]
I saw the same issue while self hosting using the docker images provided on docker-hub and github-packages.
Then I did a docker build using the Dockerfile from latest main branch and that did not have this issue.
I think this issue was fixed in #1368 and is not present in the latest release tag. Not sure what is deployed on it-tools.tech.

**Comment by ynazar1** [comment]
The fix for #1368 been merged about a week ago into mainline so the bug still stands until a new nightly (1 months old) or latest (3 months) is published.

**Comment by Adamou02** [comment]
For me the button is working from the main page. 
But when I'm inside a tool as `https://tools.mydomain.com/base64-string-converter`, then I can't add it to fav

**Comment by sharevb** [comment]
Hi @r007d4nc3 @vineet3996 @Adamou02 @ynazar1 @marinkaberg it should work in my fork

And if you are interested in an up to date version of it-tools, with many improvements, new tools, and bug fixes, as this repo is almost no more maintained, I made a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)

**Comment by willjayyyy** [comment]
The original project appears to have stopped being maintained. I forked a new branch and refactored i18n, the UI, and other aspects. The repository is currently active.

[next-tools-repository](https://github.com/willjayyyy/next-tools)
[next-tools-webside](https://next-tools.dev/)

**Comment by Adamou02** [comment]
Stop sending message please. We all know project is dead. Many forks are online now.

**Comment by JannetGen** [comment]
Yeah, that makes sense. I’d also check whether the issue is specific to one browser or environment before changing anything in the app. Testing it in a clean/private window can quickly rule out cached data, extensions, or local settings causing the problem.
