### ISSUE TITLE
[BUG]  big numbers not well handled by integer base converter

### ISSUE THREAD

**Issue by fastfailure** [CorentinTh/it-tools#452]
**Which tool is impacted?**
Integer base converter

**To Reproduce**
- Input base = 16
- Input number = `ffffffffffffff`

**Expected behavior**
Do a correct conversion or message to the user that the number is to big to be converted 

**Screenshots**
![image](https://github.com/CorentinTh/it-tools/assets/41572167/27b39548-166c-4ace-8915-7230a3074f73)

**Configuration (please complete the following information):**

- Device: PC
- OS: NixOS
- Browser Firefox
- Version 114.0.1

Thank you for your work on this useful project!

**Comment by sharevb** [comment]
Hi @CorentinTh and @fastfailure , corrected in my PR #872

**Comment by jamest-pin** [comment]
Still appears to be present.
![image](https://github.com/CorentinTh/it-tools/assets/138646078/59d597ca-bbc6-4de4-988d-0f8f6355bc87)

**Comment by sharevb** [comment]
Hi @jamest-pin, fixed in the PR (https://it-tools-git-fork-sharevb-fix-3341af-corentin-thomasset-s-team.vercel.app/base-converter) but unfortunately not already merged by @CorentinTh. Could you please take a look ? thanks

**Comment by CorentinTh** [comment]
Merged :fire: 
Sorry for the delay :pray:
